# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /vscp/vscp/vscp/vscp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /vscp/vscp/vscp/vscp

# Include any dependencies generated for this target.
include CMakeFiles/vscp_demo.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/vscp_demo.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/vscp_demo.dir/flags.make

CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.o: CMakeFiles/vscp_demo.dir/flags.make
CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.o: /vscp/vscp/vscp/examples/vscp_demo.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building C object CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.o   -c /vscp/vscp/vscp/examples/vscp_demo.c

CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /vscp/vscp/vscp/examples/vscp_demo.c > CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.i

CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /vscp/vscp/vscp/examples/vscp_demo.c -o CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.s

CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.o.requires:

.PHONY : CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.o.requires

CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.o.provides: CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.o.requires
	$(MAKE) -f CMakeFiles/vscp_demo.dir/build.make CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.o.provides.build
.PHONY : CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.o.provides

CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.o.provides.build: CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.o


# Object files for target vscp_demo
vscp_demo_OBJECTS = \
"CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.o"

# External object files for target vscp_demo
vscp_demo_EXTERNAL_OBJECTS =

vscp_demo: CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.o
vscp_demo: CMakeFiles/vscp_demo.dir/build.make
vscp_demo: libvscp.so
vscp_demo: librg-thread.so
vscp_demo: libhttp_util.so
vscp_demo: liblwm2m.so
vscp_demo: CMakeFiles/vscp_demo.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Linking C executable vscp_demo"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/vscp_demo.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/vscp_demo.dir/build: vscp_demo

.PHONY : CMakeFiles/vscp_demo.dir/build

CMakeFiles/vscp_demo.dir/requires: CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.o.requires

.PHONY : CMakeFiles/vscp_demo.dir/requires

CMakeFiles/vscp_demo.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/vscp_demo.dir/cmake_clean.cmake
.PHONY : CMakeFiles/vscp_demo.dir/clean

CMakeFiles/vscp_demo.dir/depend:
	cd /vscp/vscp/vscp/vscp && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /vscp/vscp/vscp/vscp /vscp/vscp/vscp/vscp /vscp/vscp/vscp/vscp /vscp/vscp/vscp/vscp /vscp/vscp/vscp/vscp/CMakeFiles/vscp_demo.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/vscp_demo.dir/depend

