# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /vscp/vscp/vscp/vscp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /vscp/vscp/vscp/vscp

# Include any dependencies generated for this target.
include CMakeFiles/rg-thread.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/rg-thread.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/rg-thread.dir/flags.make

CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/lib.o: CMakeFiles/rg-thread.dir/flags.make
CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/lib.o: /vscp/vscp/vscp/rg_thread/lib.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building C object CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/lib.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/lib.o   -c /vscp/vscp/vscp/rg_thread/lib.c

CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/lib.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/lib.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /vscp/vscp/vscp/rg_thread/lib.c > CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/lib.i

CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/lib.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/lib.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /vscp/vscp/vscp/rg_thread/lib.c -o CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/lib.s

CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/lib.o.requires:

.PHONY : CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/lib.o.requires

CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/lib.o.provides: CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/lib.o.requires
	$(MAKE) -f CMakeFiles/rg-thread.dir/build.make CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/lib.o.provides.build
.PHONY : CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/lib.o.provides

CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/lib.o.provides.build: CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/lib.o


CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/rg_thread.o: CMakeFiles/rg-thread.dir/flags.make
CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/rg_thread.o: /vscp/vscp/vscp/rg_thread/rg_thread.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building C object CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/rg_thread.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/rg_thread.o   -c /vscp/vscp/vscp/rg_thread/rg_thread.c

CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/rg_thread.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/rg_thread.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /vscp/vscp/vscp/rg_thread/rg_thread.c > CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/rg_thread.i

CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/rg_thread.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/rg_thread.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /vscp/vscp/vscp/rg_thread/rg_thread.c -o CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/rg_thread.s

CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/rg_thread.o.requires:

.PHONY : CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/rg_thread.o.requires

CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/rg_thread.o.provides: CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/rg_thread.o.requires
	$(MAKE) -f CMakeFiles/rg-thread.dir/build.make CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/rg_thread.o.provides.build
.PHONY : CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/rg_thread.o.provides

CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/rg_thread.o.provides.build: CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/rg_thread.o


CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/timeutil.o: CMakeFiles/rg-thread.dir/flags.make
CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/timeutil.o: /vscp/vscp/vscp/rg_thread/timeutil.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building C object CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/timeutil.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/timeutil.o   -c /vscp/vscp/vscp/rg_thread/timeutil.c

CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/timeutil.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/timeutil.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /vscp/vscp/vscp/rg_thread/timeutil.c > CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/timeutil.i

CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/timeutil.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/timeutil.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /vscp/vscp/vscp/rg_thread/timeutil.c -o CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/timeutil.s

CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/timeutil.o.requires:

.PHONY : CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/timeutil.o.requires

CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/timeutil.o.provides: CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/timeutil.o.requires
	$(MAKE) -f CMakeFiles/rg-thread.dir/build.make CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/timeutil.o.provides.build
.PHONY : CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/timeutil.o.provides

CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/timeutil.o.provides.build: CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/timeutil.o


# Object files for target rg-thread
rg__thread_OBJECTS = \
"CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/lib.o" \
"CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/rg_thread.o" \
"CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/timeutil.o"

# External object files for target rg-thread
rg__thread_EXTERNAL_OBJECTS =

librg-thread.so: CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/lib.o
librg-thread.so: CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/rg_thread.o
librg-thread.so: CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/timeutil.o
librg-thread.so: CMakeFiles/rg-thread.dir/build.make
librg-thread.so: CMakeFiles/rg-thread.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Linking C shared library librg-thread.so"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/rg-thread.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/rg-thread.dir/build: librg-thread.so

.PHONY : CMakeFiles/rg-thread.dir/build

CMakeFiles/rg-thread.dir/requires: CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/lib.o.requires
CMakeFiles/rg-thread.dir/requires: CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/rg_thread.o.requires
CMakeFiles/rg-thread.dir/requires: CMakeFiles/rg-thread.dir/vscp/vscp/vscp/rg_thread/timeutil.o.requires

.PHONY : CMakeFiles/rg-thread.dir/requires

CMakeFiles/rg-thread.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/rg-thread.dir/cmake_clean.cmake
.PHONY : CMakeFiles/rg-thread.dir/clean

CMakeFiles/rg-thread.dir/depend:
	cd /vscp/vscp/vscp/vscp && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /vscp/vscp/vscp/vscp /vscp/vscp/vscp/vscp /vscp/vscp/vscp/vscp /vscp/vscp/vscp/vscp /vscp/vscp/vscp/vscp/CMakeFiles/rg-thread.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/rg-thread.dir/depend

