# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /vscp/vscp/vscp/vscp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /vscp/vscp/vscp/vscp

# Include any dependencies generated for this target.
include CMakeFiles/lwm2m.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/lwm2m.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/lwm2m.dir/flags.make

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.o: CMakeFiles/lwm2m.dir/flags.make
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.o: /vscp/vscp/vscp/wakaama/core/liblwm2m.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building C object CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.o   -c /vscp/vscp/vscp/wakaama/core/liblwm2m.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /vscp/vscp/vscp/wakaama/core/liblwm2m.c > CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.i

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /vscp/vscp/vscp/wakaama/core/liblwm2m.c -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.s

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.o.requires:

.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.o.requires

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.o.provides: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.o.requires
	$(MAKE) -f CMakeFiles/lwm2m.dir/build.make CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.o.provides.build
.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.o.provides

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.o.provides.build: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.o


CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.o: CMakeFiles/lwm2m.dir/flags.make
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.o: /vscp/vscp/vscp/wakaama/core/uri.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building C object CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.o   -c /vscp/vscp/vscp/wakaama/core/uri.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /vscp/vscp/vscp/wakaama/core/uri.c > CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.i

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /vscp/vscp/vscp/wakaama/core/uri.c -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.s

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.o.requires:

.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.o.requires

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.o.provides: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.o.requires
	$(MAKE) -f CMakeFiles/lwm2m.dir/build.make CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.o.provides.build
.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.o.provides

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.o.provides.build: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.o


CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.o: CMakeFiles/lwm2m.dir/flags.make
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.o: /vscp/vscp/vscp/wakaama/core/utils.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building C object CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.o   -c /vscp/vscp/vscp/wakaama/core/utils.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /vscp/vscp/vscp/wakaama/core/utils.c > CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.i

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /vscp/vscp/vscp/wakaama/core/utils.c -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.s

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.o.requires:

.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.o.requires

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.o.provides: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.o.requires
	$(MAKE) -f CMakeFiles/lwm2m.dir/build.make CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.o.provides.build
.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.o.provides

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.o.provides.build: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.o


CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.o: CMakeFiles/lwm2m.dir/flags.make
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.o: /vscp/vscp/vscp/wakaama/core/objects.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building C object CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.o   -c /vscp/vscp/vscp/wakaama/core/objects.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /vscp/vscp/vscp/wakaama/core/objects.c > CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.i

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /vscp/vscp/vscp/wakaama/core/objects.c -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.s

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.o.requires:

.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.o.requires

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.o.provides: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.o.requires
	$(MAKE) -f CMakeFiles/lwm2m.dir/build.make CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.o.provides.build
.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.o.provides

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.o.provides.build: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.o


CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.o: CMakeFiles/lwm2m.dir/flags.make
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.o: /vscp/vscp/vscp/wakaama/core/tlv.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building C object CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.o   -c /vscp/vscp/vscp/wakaama/core/tlv.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /vscp/vscp/vscp/wakaama/core/tlv.c > CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.i

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /vscp/vscp/vscp/wakaama/core/tlv.c -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.s

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.o.requires:

.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.o.requires

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.o.provides: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.o.requires
	$(MAKE) -f CMakeFiles/lwm2m.dir/build.make CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.o.provides.build
.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.o.provides

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.o.provides.build: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.o


CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.o: CMakeFiles/lwm2m.dir/flags.make
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.o: /vscp/vscp/vscp/wakaama/core/data.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Building C object CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.o   -c /vscp/vscp/vscp/wakaama/core/data.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /vscp/vscp/vscp/wakaama/core/data.c > CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.i

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /vscp/vscp/vscp/wakaama/core/data.c -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.s

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.o.requires:

.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.o.requires

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.o.provides: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.o.requires
	$(MAKE) -f CMakeFiles/lwm2m.dir/build.make CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.o.provides.build
.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.o.provides

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.o.provides.build: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.o


CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.o: CMakeFiles/lwm2m.dir/flags.make
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.o: /vscp/vscp/vscp/wakaama/core/list.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Building C object CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.o   -c /vscp/vscp/vscp/wakaama/core/list.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /vscp/vscp/vscp/wakaama/core/list.c > CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.i

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /vscp/vscp/vscp/wakaama/core/list.c -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.s

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.o.requires:

.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.o.requires

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.o.provides: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.o.requires
	$(MAKE) -f CMakeFiles/lwm2m.dir/build.make CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.o.provides.build
.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.o.provides

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.o.provides.build: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.o


CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.o: CMakeFiles/lwm2m.dir/flags.make
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.o: /vscp/vscp/vscp/wakaama/core/packet.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_8) "Building C object CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.o   -c /vscp/vscp/vscp/wakaama/core/packet.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /vscp/vscp/vscp/wakaama/core/packet.c > CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.i

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /vscp/vscp/vscp/wakaama/core/packet.c -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.s

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.o.requires:

.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.o.requires

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.o.provides: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.o.requires
	$(MAKE) -f CMakeFiles/lwm2m.dir/build.make CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.o.provides.build
.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.o.provides

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.o.provides.build: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.o


CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.o: CMakeFiles/lwm2m.dir/flags.make
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.o: /vscp/vscp/vscp/wakaama/core/transaction.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_9) "Building C object CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.o   -c /vscp/vscp/vscp/wakaama/core/transaction.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /vscp/vscp/vscp/wakaama/core/transaction.c > CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.i

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /vscp/vscp/vscp/wakaama/core/transaction.c -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.s

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.o.requires:

.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.o.requires

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.o.provides: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.o.requires
	$(MAKE) -f CMakeFiles/lwm2m.dir/build.make CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.o.provides.build
.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.o.provides

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.o.provides.build: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.o


CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.o: CMakeFiles/lwm2m.dir/flags.make
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.o: /vscp/vscp/vscp/wakaama/core/registration.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_10) "Building C object CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.o   -c /vscp/vscp/vscp/wakaama/core/registration.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /vscp/vscp/vscp/wakaama/core/registration.c > CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.i

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /vscp/vscp/vscp/wakaama/core/registration.c -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.s

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.o.requires:

.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.o.requires

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.o.provides: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.o.requires
	$(MAKE) -f CMakeFiles/lwm2m.dir/build.make CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.o.provides.build
.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.o.provides

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.o.provides.build: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.o


CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.o: CMakeFiles/lwm2m.dir/flags.make
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.o: /vscp/vscp/vscp/wakaama/core/bootstrap.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_11) "Building C object CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.o   -c /vscp/vscp/vscp/wakaama/core/bootstrap.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /vscp/vscp/vscp/wakaama/core/bootstrap.c > CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.i

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /vscp/vscp/vscp/wakaama/core/bootstrap.c -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.s

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.o.requires:

.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.o.requires

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.o.provides: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.o.requires
	$(MAKE) -f CMakeFiles/lwm2m.dir/build.make CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.o.provides.build
.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.o.provides

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.o.provides.build: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.o


CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.o: CMakeFiles/lwm2m.dir/flags.make
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.o: /vscp/vscp/vscp/wakaama/core/management.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_12) "Building C object CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.o   -c /vscp/vscp/vscp/wakaama/core/management.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /vscp/vscp/vscp/wakaama/core/management.c > CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.i

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /vscp/vscp/vscp/wakaama/core/management.c -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.s

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.o.requires:

.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.o.requires

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.o.provides: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.o.requires
	$(MAKE) -f CMakeFiles/lwm2m.dir/build.make CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.o.provides.build
.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.o.provides

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.o.provides.build: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.o


CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.o: CMakeFiles/lwm2m.dir/flags.make
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.o: /vscp/vscp/vscp/wakaama/core/observe.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_13) "Building C object CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.o   -c /vscp/vscp/vscp/wakaama/core/observe.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /vscp/vscp/vscp/wakaama/core/observe.c > CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.i

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /vscp/vscp/vscp/wakaama/core/observe.c -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.s

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.o.requires:

.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.o.requires

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.o.provides: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.o.requires
	$(MAKE) -f CMakeFiles/lwm2m.dir/build.make CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.o.provides.build
.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.o.provides

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.o.provides.build: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.o


CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.o: CMakeFiles/lwm2m.dir/flags.make
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.o: /vscp/vscp/vscp/wakaama/core/json.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_14) "Building C object CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.o   -c /vscp/vscp/vscp/wakaama/core/json.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /vscp/vscp/vscp/wakaama/core/json.c > CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.i

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /vscp/vscp/vscp/wakaama/core/json.c -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.s

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.o.requires:

.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.o.requires

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.o.provides: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.o.requires
	$(MAKE) -f CMakeFiles/lwm2m.dir/build.make CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.o.provides.build
.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.o.provides

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.o.provides.build: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.o


CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.o: CMakeFiles/lwm2m.dir/flags.make
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.o: /vscp/vscp/vscp/wakaama/core/discover.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_15) "Building C object CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.o   -c /vscp/vscp/vscp/wakaama/core/discover.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /vscp/vscp/vscp/wakaama/core/discover.c > CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.i

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /vscp/vscp/vscp/wakaama/core/discover.c -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.s

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.o.requires:

.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.o.requires

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.o.provides: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.o.requires
	$(MAKE) -f CMakeFiles/lwm2m.dir/build.make CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.o.provides.build
.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.o.provides

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.o.provides.build: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.o


CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.o: CMakeFiles/lwm2m.dir/flags.make
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.o: /vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_16) "Building C object CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.o   -c /vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.c > CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.i

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.c -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.s

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.o.requires:

.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.o.requires

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.o.provides: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.o.requires
	$(MAKE) -f CMakeFiles/lwm2m.dir/build.make CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.o.provides.build
.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.o.provides

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.o.provides.build: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.o


CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/platform.o: CMakeFiles/lwm2m.dir/flags.make
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/platform.o: /vscp/vscp/vscp/wakaama/examples/shared/platform.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_17) "Building C object CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/platform.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/platform.o   -c /vscp/vscp/vscp/wakaama/examples/shared/platform.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/platform.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/platform.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /vscp/vscp/vscp/wakaama/examples/shared/platform.c > CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/platform.i

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/platform.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/platform.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /vscp/vscp/vscp/wakaama/examples/shared/platform.c -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/platform.s

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/platform.o.requires:

.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/platform.o.requires

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/platform.o.provides: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/platform.o.requires
	$(MAKE) -f CMakeFiles/lwm2m.dir/build.make CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/platform.o.provides.build
.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/platform.o.provides

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/platform.o.provides.build: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/platform.o


CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.o: CMakeFiles/lwm2m.dir/flags.make
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.o: /vscp/vscp/vscp/wakaama/examples/shared/memtrace.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_18) "Building C object CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.o   -c /vscp/vscp/vscp/wakaama/examples/shared/memtrace.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /vscp/vscp/vscp/wakaama/examples/shared/memtrace.c > CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.i

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /vscp/vscp/vscp/wakaama/examples/shared/memtrace.c -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.s

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.o.requires:

.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.o.requires

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.o.provides: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.o.requires
	$(MAKE) -f CMakeFiles/lwm2m.dir/build.make CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.o.provides.build
.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.o.provides

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.o.provides.build: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.o


CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.o: CMakeFiles/lwm2m.dir/flags.make
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.o: /vscp/vscp/vscp/wakaama/examples/shared/connection.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_19) "Building C object CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.o"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.o   -c /vscp/vscp/vscp/wakaama/examples/shared/connection.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.i"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /vscp/vscp/vscp/wakaama/examples/shared/connection.c > CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.i

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.s"
	/usr/bin/cc  $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /vscp/vscp/vscp/wakaama/examples/shared/connection.c -o CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.s

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.o.requires:

.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.o.requires

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.o.provides: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.o.requires
	$(MAKE) -f CMakeFiles/lwm2m.dir/build.make CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.o.provides.build
.PHONY : CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.o.provides

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.o.provides.build: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.o


# Object files for target lwm2m
lwm2m_OBJECTS = \
"CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.o" \
"CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.o" \
"CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.o" \
"CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.o" \
"CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.o" \
"CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.o" \
"CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.o" \
"CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.o" \
"CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.o" \
"CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.o" \
"CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.o" \
"CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.o" \
"CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.o" \
"CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.o" \
"CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.o" \
"CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.o" \
"CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/platform.o" \
"CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.o" \
"CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.o"

# External object files for target lwm2m
lwm2m_EXTERNAL_OBJECTS =

liblwm2m.so: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.o
liblwm2m.so: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.o
liblwm2m.so: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.o
liblwm2m.so: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.o
liblwm2m.so: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.o
liblwm2m.so: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.o
liblwm2m.so: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.o
liblwm2m.so: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.o
liblwm2m.so: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.o
liblwm2m.so: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.o
liblwm2m.so: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.o
liblwm2m.so: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.o
liblwm2m.so: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.o
liblwm2m.so: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.o
liblwm2m.so: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.o
liblwm2m.so: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.o
liblwm2m.so: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/platform.o
liblwm2m.so: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.o
liblwm2m.so: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.o
liblwm2m.so: CMakeFiles/lwm2m.dir/build.make
liblwm2m.so: CMakeFiles/lwm2m.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/vscp/vscp/vscp/vscp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_20) "Linking C shared library liblwm2m.so"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/lwm2m.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/lwm2m.dir/build: liblwm2m.so

.PHONY : CMakeFiles/lwm2m.dir/build

CMakeFiles/lwm2m.dir/requires: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.o.requires
CMakeFiles/lwm2m.dir/requires: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.o.requires
CMakeFiles/lwm2m.dir/requires: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.o.requires
CMakeFiles/lwm2m.dir/requires: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.o.requires
CMakeFiles/lwm2m.dir/requires: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.o.requires
CMakeFiles/lwm2m.dir/requires: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.o.requires
CMakeFiles/lwm2m.dir/requires: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.o.requires
CMakeFiles/lwm2m.dir/requires: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.o.requires
CMakeFiles/lwm2m.dir/requires: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.o.requires
CMakeFiles/lwm2m.dir/requires: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.o.requires
CMakeFiles/lwm2m.dir/requires: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.o.requires
CMakeFiles/lwm2m.dir/requires: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.o.requires
CMakeFiles/lwm2m.dir/requires: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.o.requires
CMakeFiles/lwm2m.dir/requires: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.o.requires
CMakeFiles/lwm2m.dir/requires: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.o.requires
CMakeFiles/lwm2m.dir/requires: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.o.requires
CMakeFiles/lwm2m.dir/requires: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/platform.o.requires
CMakeFiles/lwm2m.dir/requires: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.o.requires
CMakeFiles/lwm2m.dir/requires: CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.o.requires

.PHONY : CMakeFiles/lwm2m.dir/requires

CMakeFiles/lwm2m.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/lwm2m.dir/cmake_clean.cmake
.PHONY : CMakeFiles/lwm2m.dir/clean

CMakeFiles/lwm2m.dir/depend:
	cd /vscp/vscp/vscp/vscp && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /vscp/vscp/vscp/vscp /vscp/vscp/vscp/vscp /vscp/vscp/vscp/vscp /vscp/vscp/vscp/vscp /vscp/vscp/vscp/vscp/CMakeFiles/lwm2m.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/lwm2m.dir/depend

