# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.o: ../rg_thread/rg_thread.h
CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.o: ../vscp/rfid_types.h
CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.o: ../vscp/vscp_client.h
CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.o: ../vscp/vscp_debug.h
CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.o: ../wakaama/core/liblwm2m.h
CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.o: ../wakaama/examples/shared/connection.h
CMakeFiles/vscp_demo.dir/vscp/vscp/vscp/examples/vscp_demo.o: /vscp/vscp/vscp/examples/vscp_demo.c

