# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.o: /vscp/vscp/vscp/wakaama/core/bootstrap.c
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.o: /vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.o: /vscp/vscp/vscp/wakaama/core/internals.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/bootstrap.o: /vscp/vscp/vscp/wakaama/core/liblwm2m.h

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.o: /vscp/vscp/vscp/wakaama/core/data.c
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.o: /vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.o: /vscp/vscp/vscp/wakaama/core/internals.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/data.o: /vscp/vscp/vscp/wakaama/core/liblwm2m.h

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.o: /vscp/vscp/vscp/wakaama/core/discover.c
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.o: /vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.o: /vscp/vscp/vscp/wakaama/core/internals.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/discover.o: /vscp/vscp/vscp/wakaama/core/liblwm2m.h

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.o: ../wakaama/core/liblwm2m.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.o: /vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.c
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.o: /vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.h

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.o: /vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.o: /vscp/vscp/vscp/wakaama/core/internals.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.o: /vscp/vscp/vscp/wakaama/core/json.c
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/json.o: /vscp/vscp/vscp/wakaama/core/liblwm2m.h

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.o: /vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.o: /vscp/vscp/vscp/wakaama/core/internals.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.o: /vscp/vscp/vscp/wakaama/core/liblwm2m.c
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/liblwm2m.o: /vscp/vscp/vscp/wakaama/core/liblwm2m.h

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.o: /vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.o: /vscp/vscp/vscp/wakaama/core/internals.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.o: /vscp/vscp/vscp/wakaama/core/liblwm2m.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/list.o: /vscp/vscp/vscp/wakaama/core/list.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.o: /vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.o: /vscp/vscp/vscp/wakaama/core/internals.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.o: /vscp/vscp/vscp/wakaama/core/liblwm2m.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/management.o: /vscp/vscp/vscp/wakaama/core/management.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.o: /vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.o: /vscp/vscp/vscp/wakaama/core/internals.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.o: /vscp/vscp/vscp/wakaama/core/liblwm2m.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/objects.o: /vscp/vscp/vscp/wakaama/core/objects.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.o: /vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.o: /vscp/vscp/vscp/wakaama/core/internals.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.o: /vscp/vscp/vscp/wakaama/core/liblwm2m.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/observe.o: /vscp/vscp/vscp/wakaama/core/observe.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.o: /vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.o: /vscp/vscp/vscp/wakaama/core/internals.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.o: /vscp/vscp/vscp/wakaama/core/liblwm2m.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/packet.o: /vscp/vscp/vscp/wakaama/core/packet.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.o: /vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.o: /vscp/vscp/vscp/wakaama/core/internals.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.o: /vscp/vscp/vscp/wakaama/core/liblwm2m.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/registration.o: /vscp/vscp/vscp/wakaama/core/registration.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.o: /vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.o: /vscp/vscp/vscp/wakaama/core/internals.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.o: /vscp/vscp/vscp/wakaama/core/liblwm2m.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/tlv.o: /vscp/vscp/vscp/wakaama/core/tlv.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.o: /vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.o: /vscp/vscp/vscp/wakaama/core/internals.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.o: /vscp/vscp/vscp/wakaama/core/liblwm2m.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/transaction.o: /vscp/vscp/vscp/wakaama/core/transaction.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.o: /vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.o: /vscp/vscp/vscp/wakaama/core/internals.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.o: /vscp/vscp/vscp/wakaama/core/liblwm2m.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/uri.o: /vscp/vscp/vscp/wakaama/core/uri.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.o: /vscp/vscp/vscp/wakaama/core/er-coap-13/er-coap-13.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.o: /vscp/vscp/vscp/wakaama/core/internals.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.o: /vscp/vscp/vscp/wakaama/core/liblwm2m.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/core/utils.o: /vscp/vscp/vscp/wakaama/core/utils.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.o: ../vscp/vscp_debug.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.o: ../wakaama/core/liblwm2m.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.o: /vscp/vscp/vscp/wakaama/examples/shared/connection.c
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/connection.o: /vscp/vscp/vscp/wakaama/examples/shared/connection.h

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.o: ../wakaama/core/er-coap-13/er-coap-13.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.o: ../wakaama/core/internals.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.o: ../wakaama/core/liblwm2m.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/memtrace.o: /vscp/vscp/vscp/wakaama/examples/shared/memtrace.c

CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/platform.o: ../wakaama/core/liblwm2m.h
CMakeFiles/lwm2m.dir/vscp/vscp/vscp/wakaama/examples/shared/platform.o: /vscp/vscp/vscp/wakaama/examples/shared/platform.c

