# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

CMakeFiles/app_gps_server.dir/vscp/vscp/vscp/app_gps/app_gps_main.o: ../rg_thread/rg_thread.h
CMakeFiles/app_gps_server.dir/vscp/vscp/vscp/app_gps/app_gps_main.o: ../vscp/rfid_types.h
CMakeFiles/app_gps_server.dir/vscp/vscp/vscp/app_gps/app_gps_main.o: ../vscp/vscp_client.h
CMakeFiles/app_gps_server.dir/vscp/vscp/vscp/app_gps/app_gps_main.o: ../vscp/vscp_debug.h
CMakeFiles/app_gps_server.dir/vscp/vscp/vscp/app_gps/app_gps_main.o: ../wakaama/core/liblwm2m.h
CMakeFiles/app_gps_server.dir/vscp/vscp/vscp/app_gps/app_gps_main.o: ../wakaama/examples/shared/connection.h
CMakeFiles/app_gps_server.dir/vscp/vscp/vscp/app_gps/app_gps_main.o: /vscp/vscp/vscp/app_gps/app_gps_main.c
CMakeFiles/app_gps_server.dir/vscp/vscp/vscp/app_gps/app_gps_main.o: /vscp/vscp/vscp/app_gps/app_gps_server.h

CMakeFiles/app_gps_server.dir/vscp/vscp/vscp/app_gps/app_gps_server.o: ../rg_thread/rg_thread.h
CMakeFiles/app_gps_server.dir/vscp/vscp/vscp/app_gps/app_gps_server.o: ../vscp/vscp_client.h
CMakeFiles/app_gps_server.dir/vscp/vscp/vscp/app_gps/app_gps_server.o: ../vscp/vscp_debug.h
CMakeFiles/app_gps_server.dir/vscp/vscp/vscp/app_gps/app_gps_server.o: ../wakaama/core/liblwm2m.h
CMakeFiles/app_gps_server.dir/vscp/vscp/vscp/app_gps/app_gps_server.o: ../wakaama/examples/shared/connection.h
CMakeFiles/app_gps_server.dir/vscp/vscp/vscp/app_gps/app_gps_server.o: /vscp/vscp/vscp/app_gps/app_gps_server.c
CMakeFiles/app_gps_server.dir/vscp/vscp/vscp/app_gps/app_gps_server.o: /vscp/vscp/vscp/app_gps/app_gps_server.h

